import type { Product, Brand, Category } from './types';

export const products: Product[] = [
  {
    id: 1,
    name: 'Rower górski XTR Pro Carbon',
    description:
      'Profesjonalny rower górski z ramą karbonową i najwyższej klasy osprzętem.',
    price: 8999,
    salePrice: 7499,
    image: '/placeholder.svg?height=300&width=300',
    category: 'rowery-gorskie',
    brand: 'Trek',
    rating: 4.9,
    reviewCount: 128,
    isOnSale: true,
    isNew: false,
    isWeeklyHit: true,
    inStock: true,
    createdAt: '2023-01-15',
  },
  {
    id: 2,
    name: 'Rower miejski City Cruiser',
    description:
      'Wygodny rower miejski z pełnym wyposażeniem do codziennej jazdy.',
    price: 2499,
    image: '/placeholder.svg?height=300&width=300',
    category: 'rowery-miejskie',
    brand: 'Kross',
    rating: 4.5,
    reviewCount: 86,
    isOnSale: false,
    isNew: true,
    inStock: true,
    createdAt: '2023-03-10',
  },
  {
    id: 3,
    name: 'Rower szosowy Speed Master',
    description: 'Lekki i szybki rower szosowy dla entuzjastów długich tras.',
    price: 5999,
    salePrice: 4999,
    image: '/placeholder.svg?height=300&width=300',
    category: 'rowery-szosowe',
    brand: 'Specialized',
    rating: 4.8,
    reviewCount: 74,
    isOnSale: true,
    isNew: false,
    isWeeklyHit: true,
    inStock: true,
    createdAt: '2023-02-05',
  },
  {
    id: 4,
    name: 'Rower elektryczny E-Power',
    description:
      'Rower elektryczny z mocnym silnikiem i długą żywotnością baterii.',
    price: 7999,
    image: '/placeholder.svg?height=300&width=300',
    category: 'rowery-elektryczne',
    brand: 'Cannondale',
    rating: 4.7,
    reviewCount: 52,
    isOnSale: false,
    isNew: true,
    inStock: true,
    createdAt: '2023-04-20',
  },
  {
    id: 5,
    name: 'Rower dziecięcy Junior Fun',
    description: 'Kolorowy i bezpieczny rower dla dzieci w wieku 6-9 lat.',
    price: 899,
    salePrice: 699,
    image: '/placeholder.svg?height=300&width=300',
    category: 'rowery-dzieciece',
    brand: 'Kross',
    rating: 4.6,
    reviewCount: 38,
    isOnSale: true,
    isNew: false,
    inStock: true,
    createdAt: '2023-01-25',
  },
  {
    id: 6,
    name: 'Kask rowerowy Safety Pro',
    description: 'Lekki i wytrzymały kask rowerowy z regulacją.',
    price: 299,
    image: '/placeholder.svg?height=300&width=300',
    category: 'kaski',
    brand: 'Giro',
    rating: 4.8,
    reviewCount: 112,
    isOnSale: false,
    isNew: false,
    isWeeklyHit: true,
    inStock: true,
    createdAt: '2023-02-15',
  },
  {
    id: 7,
    name: 'Lampka rowerowa Night Rider',
    description: 'Mocna lampka rowerowa z długim czasem pracy na baterii.',
    price: 149,
    salePrice: 119,
    image: '/placeholder.svg?height=300&width=300',
    category: 'akcesoria',
    brand: 'CatEye',
    rating: 4.5,
    reviewCount: 67,
    isOnSale: true,
    isNew: false,
    inStock: true,
    createdAt: '2023-03-05',
  },
  {
    id: 8,
    name: 'Rower górski Trail Blazer',
    description: 'Wszechstronny rower górski do jazdy po szlakach.',
    price: 3999,
    image: '/placeholder.svg?height=300&width=300',
    category: 'rowery-gorskie',
    brand: 'Scott',
    rating: 4.6,
    reviewCount: 48,
    isOnSale: false,
    isNew: true,
    inStock: true,
    createdAt: '2023-04-10',
  },
  {
    id: 9,
    name: 'Rower miejski Urban Style',
    description: 'Stylowy rower miejski z wygodną pozycją jazdy.',
    price: 1999,
    salePrice: 1699,
    image: '/placeholder.svg?height=300&width=300',
    category: 'rowery-miejskie',
    brand: 'Romet',
    rating: 4.4,
    reviewCount: 35,
    isOnSale: true,
    isNew: false,
    inStock: true,
    createdAt: '2023-02-20',
  },
  {
    id: 10,
    name: 'Rower szosowy Aero Dynamic',
    description: 'Aerodynamiczny rower szosowy dla wymagających kolarzy.',
    price: 6999,
    image: '/placeholder.svg?height=300&width=300',
    category: 'rowery-szosowe',
    brand: 'Giant',
    rating: 4.9,
    reviewCount: 42,
    isOnSale: false,
    isNew: true,
    isWeeklyHit: true,
    inStock: true,
    createdAt: '2023-03-25',
  },
  {
    id: 11,
    name: 'Rower elektryczny City E-Bike',
    description: 'Miejski rower elektryczny z zasięgiem do 80 km.',
    price: 5999,
    salePrice: 5499,
    image: '/placeholder.svg?height=300&width=300',
    category: 'rowery-elektryczne',
    brand: 'Cube',
    rating: 4.7,
    reviewCount: 29,
    isOnSale: true,
    isNew: false,
    inStock: true,
    createdAt: '2023-01-30',
  },
  {
    id: 12,
    name: 'Rower dziecięcy Adventure Kids',
    description: 'Wytrzymały rower dla dzieci lubiących przygody.',
    price: 799,
    image: '/placeholder.svg?height=300&width=300',
    category: 'rowery-dzieciece',
    brand: 'Kross',
    rating: 4.5,
    reviewCount: 24,
    isOnSale: false,
    isNew: true,
    inStock: true,
    createdAt: '2023-04-05',
  },
];

export const brands: Brand[] = [
  {
    id: 1,
    name: 'Trek',
    slug: 'trek',
    logo: '/placeholder.svg?height=60&width=120',
  },
  {
    id: 2,
    name: 'Specialized',
    slug: 'specialized',
    logo: '/placeholder.svg?height=60&width=120',
  },
  {
    id: 3,
    name: 'Cannondale',
    slug: 'cannondale',
    logo: '/placeholder.svg?height=60&width=120',
  },
  {
    id: 4,
    name: 'Giant',
    slug: 'giant',
    logo: '/placeholder.svg?height=60&width=120',
  },
  {
    id: 5,
    name: 'Scott',
    slug: 'scott',
    logo: '/placeholder.svg?height=60&width=120',
  },
  {
    id: 6,
    name: 'Kross',
    slug: 'kross',
    logo: '/placeholder.svg?height=60&width=120',
  },
  {
    id: 7,
    name: 'Cube',
    slug: 'cube',
    logo: '/placeholder.svg?height=60&width=120',
  },
  {
    id: 8,
    name: 'Romet',
    slug: 'romet',
    logo: '/placeholder.svg?height=60&width=120',
  },
  {
    id: 9,
    name: 'Giro',
    slug: 'giro',
    logo: '/placeholder.svg?height=60&width=120',
  },
  {
    id: 10,
    name: 'CatEye',
    slug: 'cateye',
    logo: '/placeholder.svg?height=60&width=120',
  },
];

export const categories: Category[] = [
  {
    id: 1,
    name: 'Rowery górskie',
    slug: 'rowery-gorskie',
  },
  {
    id: 2,
    name: 'Rowery miejskie',
    slug: 'rowery-miejskie',
  },
  {
    id: 3,
    name: 'Rowery szosowe',
    slug: 'rowery-szosowe',
  },
  {
    id: 4,
    name: 'Rowery elektryczne',
    slug: 'rowery-elektryczne',
  },
  {
    id: 5,
    name: 'Rowery dziecięce',
    slug: 'rowery-dzieciece',
  },
  {
    id: 6,
    name: 'Kaski',
    slug: 'kaski',
  },
  {
    id: 7,
    name: 'Akcesoria',
    slug: 'akcesoria',
  },
  {
    id: 8,
    name: 'Części',
    slug: 'czesci',
  },
  {
    id: 9,
    name: 'Odzież',
    slug: 'odziez',
  },
];
